In [46]:
import pandas as pd

filepath = 'https://raw.githubusercontent.com/LondonEnergyMap/model_data/master/domestic/combined_needepc.csv'
df_all = pd.read_csv(filepath)
df_all.head()

,hid,imd,type,form,exposedsides,tfa,epc,age,nroom,maingas,gcons,econs,gmeters,emeters
0,3221499468,6.0,flat,detached,4.0,48.30,2,1.0,1,1,5636.993076,2874.8,7.0,7.0
1,2290543668,6.0,flat,mid-terrace,2.0,70.85,2,3.0,3,1,5636.993076,2874.8,7.0,7.0
2,6015699968,6.0,flat,mid-terrace,2.0,66.00,2,1.0,3,1,5636.993076,2874.8,7.0,7.0
3,9939448868,6.0,flat,mid-terrace,2.0,66.00,2,1.0,3,1,5636.993076,2874.8,7.0,7.0
4,1536490868,6.0,flat,enclosed mid-terrace,1.5,111.00,2,1.0,4,1,5636.993076,2874.8,7.0,7.0

In [47]:
df_all.shape

(54963, 14)

In [48]:
df = df_all[(df_all.gmeters<=7) & (df_all.emeters<=7)]
df.shape

(16394, 14)

In [67]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# temp = df_all[(df_all.gmeters<=7) & (df_all.emeters<=7)]

temp = df_all[(df_all.gmeters > 1) & (df_all.emeters > 1)]

# temp = temp[temp.nroom > 5]
# temp = df_all
temp.head()
temp.nroom.unique()

array([ 1,  3,  4,  2,  5,  6,  8,  7,  9, 10])

In [69]:
# x = temp[['imd', 'tfa', 'epc', 'age', 'nroom', 'exposedsides', 'maingas']]
x = temp[['tfa', 'epc', 'age', 'nroom', 'exposedsides', 'maingas']] #'imd'
y = temp[['gcons', 'econs']]

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2, random_state=42)

lrmodel = LinearRegression()
lrmodel.fit(x_train, y_train)
predictions = lrmodel.predict(x_test)
scores = lrmodel.score(x_train, y_train)
scores

0.5296863254254113

In [73]:
gcons_predict, econs_predict = map(list, zip(*predictions))

In [79]:
y_test['gcons1'] = gcons_predict

/Users/dora/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

              gcons    econs        gcons1
35787  17230.249131  2681.40  17230.249131
29580  15230.745408  2542.45  15230.745408
8546    9578.488635  5866.80   9578.488635
46308  10556.026118  2714.40  10556.026118
33599  16757.376664  2371.60  16757.376664
32039  11507.874123   804.80  11507.874123
39109  14636.111125  3463.40  14636.111125
8684   28384.816227  3697.00  28384.816227
2476    7476.548416  2520.80   7476.548416
40805   6626.011321  2619.70   6626.011321
29319  22644.949289  4862.50  22644.949289
29662   9252.708954  1563.30   9252.708954
2767    9310.563378  2391.40   9310.563378
7272   12228.324568  3825.05  12228.324568
29773  11464.068358  2053.40  11464.068358
13256  17912.530117  4833.00  17912.530117
40339   8108.658122  1884.90   8108.658122
30038  26325.113770  6684.00  26325.113770
29741   9260.844575  3083.40   9260.844575
14421   5538.453324  2325.20   5538.453324
2354   19251.120693  5743.10  19251.120693
42450  17732.043822  3301.80  17732.043822
42143   7658.814268  1325.30   7658.814268
23865  13344.619565  3984.00  13344.619565
16140  17117.940330  2851.30  17117.940330
12510  10912.593686  2951.20  10912.593686
29016   8092.720656  3120.95   8092.720656
40819  11084.110799  2312.55  11084.110799
26350  17905.646397  3310.40  17905.646397
19886   9571.604915  1699.80   9571.604915
...             ...      ...           ...
1185   10558.787390  2557.85  10558.787390
45948  10133.945968  3202.80  10133.945968
10172   4834.335939  1850.55   4834.335939
11972  20630.326597  3390.30  20630.326597
5386   12998.351004  1686.10  12998.351004
17255  12919.562626  2737.95  12919.562626
44884  13942.907337  2431.70  13942.907337
28650  11077.404630  3139.40  11077.404630
42921   7475.111551  1488.20   7475.111551
24152   7020.411546  1980.95   7020.411546
42671  30129.208351  5810.10  30129.208351
3979   16101.385568  3548.85  16101.385568
7090   11038.956156  2017.60  11038.956156
48542   8068.115353  3085.75   8068.115353
41041  12646.919573  1524.60  12646.919573
28622   9997.889861  2824.25   9997.889861
41827  15822.818654  3357.20  15822.818654
24344  14551.574600  2968.15  14551.574600
18968  15747.014530  3338.15  15747.014530
27903  13565.411012  2884.75  13565.411012
20767  10562.765449  2334.10  10562.765449
44178   9097.691199  2941.15   9097.691199
24407   7572.187509  2632.20   7572.187509
16530  15926.150497  3241.40  15926.150497
18427  10768.696236  4514.70  10768.696236
24702  34810.864609  5979.35  34810.864609
7104   17354.436430  3418.20  17354.436430
26075  11763.338249  2408.80  11763.338249
38361   9273.772472  2297.05   9273.772472
4056   13988.061981  3164.80  13988.061981

[9970 rows x 3 columns]