In [62]:
import pandas as pd

epc_filepath = 'https://media.githubusercontent.com/media/LondonEnergyMap/cleandata/master/epc/domestic/epcdom_10meters.csv'
dfepc = pd.read_csv(epc_filepath)

dfepc.head()

,pcode,bref,curr_enr,curr_encons,prop_type,builtform,la,transact_type,tfa,mainsgas,nrooms,wall,gasmeters,gasmid,elecmeters,elecmid
0,EC4Y 8DU,3221499468,C,9662,Flat,Detached,City of London,not recorded,48.30,Y,1,Wall,7.0,5636.993076,7.0,2874.8
1,EC4Y 8DU,2290543668,C,172,Flat,Mid-Terrace,City of London,rental (private),70.85,Y,3,"System built, as built, no insulation (assumed)",7.0,5636.993076,7.0,2874.8
2,EC4Y 8DU,6015699968,C,146,Flat,Mid-Terrace,City of London,marketed sale,66.00,Y,3,"Solid brick, as built, no insulation (assumed)",7.0,5636.993076,7.0,2874.8
3,EC4Y 8DU,9939448868,C,139,Flat,Mid-Terrace,City of London,marketed sale,66.00,Y,3,"Solid brick, as built, no insulation (assumed)",7.0,5636.993076,7.0,2874.8
4,EC4Y 8DU,1536490868,C,154,Flat,Enclosed Mid-Terrace,City of London,marketed sale,111.00,Y,4,"Solid brick, as built, no insulation (assumed)",7.0,5636.993076,7.0,2874.8

In [63]:
# pcode1 = dfepc.pcode.iloc[0:9999]
# pcode2 = dfepc.pcode.iloc[10000:19999]
# pcode3 = dfepc.pcode.iloc[20000:29999]
# pcode4 = dfepc.pcode.iloc[30000:39999]
# pcode5 = dfepc.pcode.iloc[40000:49999]
# pcode6 = dfepc.pcode.iloc[50000:]

In [64]:
# pcode1.to_csv('pcode1.csv', index=False)
# pcode2.to_csv('pcode2.csv', index=False)
# pcode3.to_csv('pcode3.csv', index=False)
# pcode4.to_csv('pcode4.csv', index=False)
# pcode5.to_csv('pcode5.csv', index=False)
# pcode6.to_csv('pcode6.csv', index=False)

In [65]:
imd_filepath = 'https://media.githubusercontent.com/media/LondonEnergyMap/cleandata/master/epc/domestic/imd/ecp10meters_pcode_imd.csv'
dfimd = pd.read_csv(imd_filepath)
dfimd.head()

,Postcode,Postcode Status,LSOA code,LSOA Name,Index of Multiple Deprivation Rank,Index of Multiple Deprivation Decile,Income Rank,Income Decile,Income Score,Employment Rank,...,Barriers to Housing and Services Rank,Barriers to Housing and Services Decile,Living Environment Rank,Living Environment Decile,IDACI Rank,IDACI Decile,IDACI Score,IDAOPI Rank,IDAOPI Decile,IDAOPI Score
0,EC4Y 8DU,Live,E01032740,City of London 001G E01032740,18868,6,31643,10,0.029,31733,...,6063,2,79,1,32367,10,0.018,32844,10,0.007
1,EC4Y 8DU,Live,E01032740,City of London 001G E01032740,18868,6,31643,10,0.029,31733,...,6063,2,79,1,32367,10,0.018,32844,10,0.007
2,EC4Y 8DU,Live,E01032740,City of London 001G E01032740,18868,6,31643,10,0.029,31733,...,6063,2,79,1,32367,10,0.018,32844,10,0.007
3,EC4Y 8DU,Live,E01032740,City of London 001G E01032740,18868,6,31643,10,0.029,31733,...,6063,2,79,1,32367,10,0.018,32844,10,0.007
4,EC4Y 8DU,Live,E01032740,City of London 001G E01032740,18868,6,31643,10,0.029,31733,...,6063,2,79,1,32367,10,0.018,32844,10,0.007

In [66]:
dfimd['Index of Multiple Deprivation Decile'].unique()

array([ 6,  7,  4,  2,  3,  1,  5,  9,  8, 10])

In [67]:
imd_dict = pd.Series(dfimd['Index of Multiple Deprivation Decile'].values, index=dfimd['Postcode']).to_dict()
imd_dict
# map postcode to deprivation index
dfepc['imd'] = dfepc.pcode.map(imd_dict)

In [75]:
# map nrooms=-1 to nroom based on floor area bands similar to NEED
import numpy as np



# first limit nrooms upper limit and area limits
n = 10
dfepc = dfepc[dfepc.nrooms <= n]

tfa_upper = n*50
tfa_lower = 30
dfepc = dfepc[(dfepc.tfa >= tfa_lower) & (dfepc.tfa <= tfa_upper)]

areabins = [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
arealabels = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
dfepc['nroomtfa'] = pd.cut(dfepc.tfa, areabins, labels=arealabels) 

dfepc['nroom'] = np.where((dfepc.nrooms == -1), dfepc.nroomtfa, dfepc.nrooms)
dfepc.head()

,pcode,bref,curr_enr,curr_encons,prop_type,builtform,la,transact_type,tfa,mainsgas,nrooms,wall,gasmeters,gasmid,elecmeters,elecmid,imd,nroomtfa,nroom
0,EC4Y 8DU,3221499468,C,9662,Flat,Detached,City of London,not recorded,48.30,Y,1,Wall,7.0,5636.993076,7.0,2874.8,6,1,1
1,EC4Y 8DU,2290543668,C,172,Flat,Mid-Terrace,City of London,rental (private),70.85,Y,3,"System built, as built, no insulation (assumed)",7.0,5636.993076,7.0,2874.8,6,2,3
2,EC4Y 8DU,6015699968,C,146,Flat,Mid-Terrace,City of London,marketed sale,66.00,Y,3,"Solid brick, as built, no insulation (assumed)",7.0,5636.993076,7.0,2874.8,6,2,3
3,EC4Y 8DU,9939448868,C,139,Flat,Mid-Terrace,City of London,marketed sale,66.00,Y,3,"Solid brick, as built, no insulation (assumed)",7.0,5636.993076,7.0,2874.8,6,2,3
4,EC4Y 8DU,1536490868,C,154,Flat,Enclosed Mid-Terrace,City of London,marketed sale,111.00,Y,4,"Solid brick, as built, no insulation (assumed)",7.0,5636.993076,7.0,2874.8,6,3,4

In [77]:
# convert property type and form to exposed sides

# create new column for number of exposed sides based on property type and form
prop_mapping = {'House': 0, 'Flat': -2, 'Bungalow': 0.5, 'Maisonette': -2,
                'Park home': 0}
built_mapping = {'Detached': 0, 'Semi-Detached': -1,
                 'End-Terrace': -1, 'Mid-Terrace': -2,
                 'Enclosed Mid-Terrace': -2.5, 'Enclosed End-Terrace': -1.5,
                 'NO DATA!': 0}

dfepc['propmap'] = dfepc.prop_type.map(prop_mapping)
dfepc['builtmap'] = dfepc.builtform.map(built_mapping)
dfepc['exposedsides'] = 6 + dfepc.propmap + dfepc.builtmap

dfepc['type'] = dfepc.prop_type.str.lower()
dfepc['form'] = dfepc.builtform.str.lower()

dfepc.head()

,pcode,bref,curr_enr,curr_encons,prop_type,builtform,la,transact_type,tfa,mainsgas,...,elecmeters,elecmid,imd,nroomtfa,nroom,propmap,builtmap,exposedsides,type,form
0,EC4Y 8DU,3221499468,C,9662,Flat,Detached,City of London,not recorded,48.30,Y,...,7.0,2874.8,6,1,1,-2.0,0.0,4.0,flat,detached
1,EC4Y 8DU,2290543668,C,172,Flat,Mid-Terrace,City of London,rental (private),70.85,Y,...,7.0,2874.8,6,2,3,-2.0,-2.0,2.0,flat,mid-terrace
2,EC4Y 8DU,6015699968,C,146,Flat,Mid-Terrace,City of London,marketed sale,66.00,Y,...,7.0,2874.8,6,2,3,-2.0,-2.0,2.0,flat,mid-terrace
3,EC4Y 8DU,9939448868,C,139,Flat,Mid-Terrace,City of London,marketed sale,66.00,Y,...,7.0,2874.8,6,2,3,-2.0,-2.0,2.0,flat,mid-terrace
4,EC4Y 8DU,1536490868,C,154,Flat,Enclosed Mid-Terrace,City of London,marketed sale,111.00,Y,...,7.0,2874.8,6,3,4,-2.0,-2.5,1.5,flat,enclosed mid-terrace

In [78]:
# convert wall and transaction type to building age

# create new column of building age based on wall description and transcation type
dfepc['wall_firstword'] = dfepc.wall.str.split().str.get(0)
wall_mapping = {'Cavity': 2, 'System': 3, 'Timber': 3}
dfepc['age'] = dfepc.wall_firstword.map(wall_mapping)
dfepc.age.fillna(1, inplace=True)
dfepc.loc[dfepc.transact_type == 'new dwelling', 'age'] = 6

In [79]:
epc_dict = {'A': 1, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6}
dfepc['epc_band'] = dfepc.curr_enr.map(epc_dict)
dfepc.head()

,pcode,bref,curr_enr,curr_encons,prop_type,builtform,la,transact_type,tfa,mainsgas,...,nroomtfa,nroom,propmap,builtmap,exposedsides,type,form,wall_firstword,age,epc_band
0,EC4Y 8DU,3221499468,C,9662,Flat,Detached,City of London,not recorded,48.30,Y,...,1,1,-2.0,0.0,4.0,flat,detached,Wall,1.0,2
1,EC4Y 8DU,2290543668,C,172,Flat,Mid-Terrace,City of London,rental (private),70.85,Y,...,2,3,-2.0,-2.0,2.0,flat,mid-terrace,System,3.0,2
2,EC4Y 8DU,6015699968,C,146,Flat,Mid-Terrace,City of London,marketed sale,66.00,Y,...,2,3,-2.0,-2.0,2.0,flat,mid-terrace,Solid,1.0,2
3,EC4Y 8DU,9939448868,C,139,Flat,Mid-Terrace,City of London,marketed sale,66.00,Y,...,2,3,-2.0,-2.0,2.0,flat,mid-terrace,Solid,1.0,2
4,EC4Y 8DU,1536490868,C,154,Flat,Enclosed Mid-Terrace,City of London,marketed sale,111.00,Y,...,3,4,-2.0,-2.5,1.5,flat,enclosed mid-terrace,Solid,1.0,2

In [80]:
dfepc.exposedsides.isnull()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
52317    False
52318    False
52319    False
52320    False
52321    False
52322    False
52323    False
52324    False
52325    False
52326    False
52328    False
52329    False
52330    False
52331    False
52332    False
52333    False
52334    False
52335    False
52336    False
52337    False
52338    False
52339    False
52340    False
52341    False
52342    False
52343    False
52344    False
52345    False
52346    False
52347    False
Name: exposedsides, Length: 49848, dtype: bool

In [81]:
notgas_filepath = 'https://raw.githubusercontent.com/LondonEnergyMap/rawdata/master/building_stock/pcode_notgas.csv'
dfnotgas = pd.read_csv(notgas_filepath)

In [82]:
dfnotgas['gas'] = 0
dfnotgas.head()

   Postcode  gas
0  AB10 1AB    0
1  AB10 1AF    0
2  AB10 1AG    0
3  AB10 1AH    0
4  AB10 1AL    0

In [83]:
notgas_dict = pd.Series(dfnotgas.gas.values, index=dfnotgas['Postcode']).to_dict()
notgas_dict

{'AB10 1AB': 0,
 'AB10 1AF': 0,
 'AB10 1AG': 0,
 'AB10 1AH': 0,
 'AB10 1AL': 0,
 'AB10 1AR': 0,
 'AB10 1AX': 0,
 'AB10 1BF': 0,
 'AB10 1BJ': 0,
 'AB10 1BR': 0,
 'AB10 1BW': 0,
 'AB10 1DB': 0,
 'AB10 1DU': 0,
 'AB10 1FL': 0,
 'AB10 1FT': 0,
 'AB10 1FY': 0,
 'AB10 1GS': 0,
 'AB10 1GZ': 0,
 'AB10 1HA': 0,
 'AB10 1JL': 0,
 'AB10 1JP': 0,
 'AB10 1LP': 0,
 'AB10 1NT': 0,
 'AB10 1PA': 0,
 'AB10 1PD': 0,
 'AB10 1PY': 0,
 'AB10 1QA': 0,
 'AB10 1QW': 0,
 'AB10 1QZ': 0,
 'AB10 1SE': 0,
 'AB10 1ST': 0,
 'AB10 1TA': 0,
 'AB10 1TB': 0,
 'AB10 1TW': 0,
 'AB10 1WB': 0,
 'AB10 1WH': 0,
 'AB10 1WP': 0,
 'AB10 1WR': 0,
 'AB10 1WS': 0,
 'AB10 1XF': 0,
 'AB10 1XG': 0,
 'AB10 1YF': 0,
 'AB10 1YR': 0,
 'AB10 1ZG': 0,
 'AB10 1ZP': 0,
 'AB10 1ZT': 0,
 'AB10 1ZU': 0,
 'AB10 1ZX': 0,
 'AB10 6AG': 0,
 'AB10 6DF': 0,
 'AB10 6DL': 0,
 'AB10 6EW': 0,
 'AB10 6FA': 0,
 'AB10 6FB': 0,
 'AB10 6LP': 0,
 'AB10 6RZ': 0,
 'AB10 6SZ': 0,
 'AB10 6WE': 0,
 'AB10 6YH': 0,
 'AB10 7FT': 0,
 'AB10 7FY': 0,
 'AB10 7GD': 0,
 'AB10 7GE': 0,
 'AB10 7GZ': 0,
 'AB10 7HG': 0,
 'AB10 7HL': 0,
 'AB10 7HW': 0,
 'AB10 7HZ': 0,
 'AB10 7NB': 0,
 'AB10 7PN': 0,
 'AB10 7QG': 0,
 'AB10 7QQ': 0,
 'AB10 7YA': 0,
 'AB11 5AF': 0,
 'AB11 5AX': 0,
 'AB11 5BS': 0,
 'AB11 5DG': 0,
 'AB11 5DW': 0,
 'AB11 5EF': 0,
 'AB11 5EP': 0,
 'AB11 5EQ': 0,
 'AB11 5FJ': 0,
 'AB11 5FT': 0,
 'AB11 5FW': 0,
 'AB11 5HB': 0,
 'AB11 5HW': 0,
 'AB11 5HX': 0,
 'AB11 5NP': 0,
 'AB11 5NS': 0,
 'AB11 5NT': 0,
 'AB11 5PA': 0,
 'AB11 5PD': 0,
 'AB11 5PF': 0,
 'AB11 5PN': 0,
 'AB11 5PS': 0,
 'AB11 5PT': 0,
 'AB11 5QA': 0,
 'AB11 5QF': 0,
 'AB11 5QH': 0,
 'AB11 5RA': 0,
 'AB11 5RE': 0,
 'AB11 5RH': 0,
 'AB11 5RN': 0,
 'AB11 5YD': 0,
 'AB11 5YL': 0,
 'AB11 5ZH': 0,
 'AB11 6AD': 0,
 'AB11 6BG': 0,
 'AB11 6BP': 0,
 'AB11 6DF': 0,
 'AB11 6DT': 0,
 'AB11 6EZ': 0,
 'AB11 6FB': 0,
 'AB11 6FF': 0,
 'AB11 6FN': 0,
 'AB11 6FR': 0,
 'AB11 6FS': 0,
 'AB11 6FW': 0,
 'AB11 6HW': 0,
 'AB11 6LX': 0,
 'AB11 6NA': 0,
 'AB11 6NL': 0,
 'AB11 6NR': 0,
 'AB11 6NW': 0,
 'AB11 6NZ': 0,
 'AB11 6PJ': 0,
 'AB11 6QF': 0,
 'AB11 6SL': 0,
 'AB11 6UU': 0,
 'AB11 6WT': 0,
 'AB11 6XF': 0,
 'AB11 6XH': 0,
 'AB11 6XZ': 0,
 'AB11 6YQ': 0,
 'AB11 6ZF': 0,
 'AB11 7WF': 0,
 'AB11 8AA': 0,
 'AB11 8BW': 0,
 'AB11 8DZ': 0,
 'AB11 8ET': 0,
 'AB11 8QX': 0,
 'AB11 8TW': 0,
 'AB11 8TX': 0,
 'AB11 8TY': 0,
 'AB11 9AD': 0,
 'AB11 9NF': 0,
 'AB11 9NW': 0,
 'AB11 9QF': 0,
 'AB11 9QG': 0,
 'AB11 9QR': 0,
 'AB11 9QT': 0,
 'AB11 9RD': 0,
 'AB11 9YQ': 0,
 'AB12 3AP': 0,
 'AB12 3AZ': 0,
 'AB12 3BD': 0,
 'AB12 3BS': 0,
 'AB12 3BX': 0,
 'AB12 3EU': 0,
 'AB12 3FL': 0,
 'AB12 3GA': 0,
 'AB12 3GF': 0,
 'AB12 3GG': 0,
 'AB12 3GS': 0,
 'AB12 3GW': 0,
 'AB12 3HA': 0,
 'AB12 3JP': 0,
 'AB12 3LJ': 0,
 'AB12 3LP': 0,
 'AB12 3LR': 0,
 'AB12 3LT': 0,
 'AB12 3NP': 0,
 'AB12 3NQ': 0,
 'AB12 3PS': 0,
 'AB12 3QA': 0,
 'AB12 3QH': 0,
 'AB12 3QQ': 0,
 'AB12 3QU': 0,
 'AB12 3RA': 0,
 'AB12 3RL': 0,
 'AB12 3RN': 0,
 'AB12 3RR': 0,
 'AB12 3RS': 0,
 'AB12 3RT': 0,
 'AB12 3SS': 0,
 'AB12 3TL': 0,
 'AB12 3TP': 0,
 'AB12 3TW': 0,
 'AB12 3TY': 0,
 'AB12 3UF': 0,
 'AB12 3WN': 0,
 'AB12 3WR': 0,
 'AB12 3XY': 0,
 'AB12 3YG': 0,
 'AB12 3YS': 0,
 'AB12 3YT': 0,
 'AB12 3ZE': 0,
 'AB12 4AA': 0,
 'AB12 4AN': 0,
 'AB12 4JS': 0,
 'AB12 4LH': 0,
 'AB12 4LP': 0,
 'AB12 4LQ': 0,
 'AB12 4NJ': 0,
 'AB12 4NN': 0,
 'AB12 4NP': 0,
 'AB12 4NR': 0,
 'AB12 4NS': 0,
 'AB12 4NT': 0,
 'AB12 4NW': 0,
 'AB12 4PU': 0,
 'AB12 4QR': 0,
 'AB12 4QT': 0,
 'AB12 4RJ': 0,
 'AB12 4RY': 0,
 'AB12 4SA': 0,
 'AB12 4SB': 0,
 'AB12 4SD': 0,
 'AB12 4SE': 0,
 'AB12 4SH': 0,
 'AB12 4SJ': 0,
 'AB12 4SL': 0,
 'AB12 4SN': 0,
 'AB12 4UU': 0,
 'AB12 4XX': 0,
 'AB12 4XZ': 0,
 'AB12 4YF': 0,
 'AB12 4YS': 0,
 'AB12 4ZD': 0,
 'AB12 5AF': 0,
 'AB12 5BZ': 0,
 'AB12 5DF': 0,
 'AB12 5FE': 0,
 'AB12 5FR': 0,
 'AB12 5GA': 0,
 'AB12 5GD': 0,
 'AB12 5GE': 0,
 'AB12 5GP': 0,
 'AB12 5GQ': 0,
 'AB12 5GR': 0,
 'AB12 5GS': 0,
 'AB12 5GY': 0,
 'AB12 5GZ': 0,
 'AB12 5LF': 0,
 'AB12 5PF': 0,
 'AB12 5QU': 0,
 'AB12 5WG': 0,
 'AB12 5XJ': 0,
 'AB12 5XL': 0,
 'AB12 5XN': 0,
 'AB12 5XP': 0,
 'AB12 5XR': 0,
 'AB12 5XS': 0,
 'AB12 5XT': 0,
 'AB12 5YA': 0,
 'AB12 5YB': 0,
 'AB12 5YQ': 0,
 'AB12 5YR': 0,
 'AB12 5YS': 0,
 'AB12 5YT': 0,
 'AB12 5YX': 0,
 'AB12 9AJ': 0,
 'AB12 9AL': 0,
 'AB12 9AX': 0,
 'AB12 9AY': 0,
 'AB12 9AZ': 0,
 'AB12 9BF': 0,
 'AB12 9BQ': 0,
 'AB12 9DE': 0,
 'AB12 9DL': 0,
 'AB12 9DT': 0,
 'AB12 9DU': 0,
 'AB12 9DX': 0,
 'AB12 9DY': 0,
 'AB12 9DZ': 0,
 'AB12 9EG': 0,
 'AB12 9EL': 0,
 'AB12 9EW': 0,
 'AB12 9EZ': 0,
 'AB12 9FA': 0,
 'AB12 9FD': 0,
 'AB12 9FE': 0,
 'AB12 9FF': 0,
 'AB12 9FH': 0,
 'AB12 9FL': 0,
 'AB12 9FN': 0,
 'AB12 9FP': 0,
 'AB12 9FQ': 0,
 'AB12 9SA': 0,
 'AB12 9SB': 0,
 'AB12 9SD': 0,
 'AB12 9SE': 0,
 'AB12 9SF': 0,
 'AB12 9SG': 0,
 'AB12 9SH': 0,
 'AB12 9SJ': 0,
 'AB12 9SL': 0,
 'AB12 9SN': 0,
 'AB12 9SP': 0,
 'AB12 9SQ': 0,
 'AB12 9SR': 0,
 'AB12 9SS': 0,
 'AB12 9ST': 0,
 'AB12 9SU': 0,
 'AB12 9SW': 0,
 'AB12 9SX': 0,
 'AB12 9SY': 0,
 'AB12 9SZ': 0,
 'AB12 9TA': 0,
 'AB12 9TB': 0,
 'AB12 9TD': 0,
 'AB12 9TE': 0,
 'AB12 9TF': 0,
 'AB12 9TG': 0,
 'AB12 9TH': 0,
 'AB12 9TJ': 0,
 'AB12 9TL': 0,
 'AB12 9TN': 0,
 'AB12 9TP': 0,
 'AB12 9TQ': 0,
 'AB12 9TR': 0,
 'AB12 9TS': 0,
 'AB12 9TT': 0,
 'AB12 9TU': 0,
 'AB12 9TW': 0,
 'AB12 9TX': 0,
 'AB12 9TY': 0,
 'AB12 9TZ': 0,
 'AB12 9UA': 0,
 'AB12 9UB': 0,
 'AB12 9UD': 0,
 'AB12 9UE': 0,
 'AB12 9UF': 0,
 'AB12 9UG': 0,
 'AB12 9UH': 0,
 'AB12 9UJ': 0,
 'AB12 9UL': 0,
 'AB12 9UN': 0,
 'AB12 9UP': 0,
 'AB12 9UQ': 0,
 'AB12 9UR': 0,
 'AB12 9US': 0,
 'AB12 9UT': 0,
 'AB12 9UU': 0,
 'AB12 9UW': 0,
 'AB12 9UX': 0,
 'AB12 9UY': 0,
 'AB12 9ZZ': 0,
 'AB13 0AE': 0,
 'AB13 0AP': 0,
 'AB13 0EQ': 0,
 'AB13 0ER': 0,
 'AB13 0ES': 0,
 'AB13 0ET': 0,
 'AB13 0EX': 0,
 'AB13 0HQ': 0,
 'AB13 0HX': 0,
 'AB13 0WW': 0,
 'AB13 0WX': 0,
 'AB13 0YF': 0,
 'AB14 0LT': 0,
 'AB14 0LU': 0,
 'AB14 0ND': 0,
 'AB14 0NJ': 0,
 'AB14 0NS': 0,
 'AB14 0NT': 0,
 'AB14 0NW': 0,
 'AB14 0NX': 0,
 'AB14 0PB': 0,
 'AB14 0PD': 0,
 'AB14 0PE': 0,
 'AB14 0PJ': 0,
 'AB14 0PL': 0,
 'AB14 0PN': 0,
 'AB14 0PP': 0,
 'AB14 0PQ': 0,
 'AB14 0PR': 0,
 'AB14 0PS': 0,
 'AB14 0PY': 0,
 'AB14 0RQ': 0,
 'AB14 0SH': 0,
 'AB14 0XH': 0,
 'AB15 4DY': 0,
 'AB15 4UG': 0,
 'AB15 5FA': 0,
 'AB15 5FD': 0,
 'AB15 5FG': 0,
 'AB15 5FH': 0,
 'AB15 5GB': 0,
 'AB15 5LD': 0,
 'AB15 5YL': 0,
 'AB15 6AG': 0,
 'AB15 6AX': 0,
 'AB15 6BY': 0,
 'AB15 6DA': 0,
 'AB15 6DF': 0,
 'AB15 6DZ': 0,
 'AB15 6EZ': 0,
 'AB15 6GU': 0,
 'AB15 6GW': 0,
 'AB15 6HR': 0,
 'AB15 6HY': 0,
 'AB15 6LS': 0,
 'AB15 6NA': 0,
 'AB15 6NB': 0,
 'AB15 6UJ': 0,
 'AB15 6WQ': 0,
 'AB15 6XH': 0,
 'AB15 7AL': 0,
 'AB15 7SG': 0,
 'AB15 7YJ': 0,
 'AB15 7YX': 0,
 'AB15 7ZB': 0,
 'AB15 8AL': 0,
 'AB15 8AS': 0,
 'AB15 8AT': 0,
 'AB15 8BB': 0,
 'AB15 8BD': 0,
 'AB15 8BJ': 0,
 'AB15 8BQ': 0,
 'AB15 8EQ': 0,
 'AB15 8ER': 0,
 'AB15 8ES': 0,
 'AB15 8ET': 0,
 'AB15 8PD': 0,
 'AB15 8PN': 0,
 'AB15 8PP': 0,
 'AB15 8PQ': 0,
 'AB15 8PR': 0,
 'AB15 8PS': 0,
 'AB15 8PX': 0,
 'AB15 8QB': 0,
 'AB15 8QD': 0,
 'AB15 8QG': 0,
 'AB15 8QJ': 0,
 'AB15 8QL': 0,
 'AB15 8QN': 0,
 'AB15 8QP': 0,
 'AB15 8QQ': 0,
 'AB15 8QR': 0,
 'AB15 8QS': 0,
 'AB15 8QT': 0,
 'AB15 8QU': 0,
 'AB15 8QW': 0,
 'AB15 8RA': 0,
 'AB15 8RB': 0,
 'AB15 8RD': 0,
 'AB15 8RJ': 0,
 'AB15 8RL': 0,
 'AB15 8RN': 0,
 'AB15 8RP': 0,
 'AB15 8RQ': 0,
 'AB15 8RR': 0,
 'AB15 8RT': 0,
 'AB15 8RX': 0,
 'AB15 8SA': 0,
 'AB15 8SJ': 0,
 'AB15 8SL': 0,
 'AB15 8SN': 0,
 'AB15 8SP': 0,
 'AB15 8SQ': 0,
 'AB15 8SR': 0,
 'AB15 8SS': 0,
 'AB15 8ST': 0,
 'AB15 8WX': 0,
 'AB15 8YT': 0,
 'AB15 9AU': 0,
 'AB15 9BE': 0,
 'AB15 9BP': 0,
 'AB15 9BT': 0,
 'AB15 9BX': 0,
 'AB15 9DA': 0,
 'AB15 9EH': 0,
 'AB15 9EN': 0,
 'AB15 9EP': 0,
 'AB15 9LW': 0,
 'AB15 9LY': 0,
 'AB15 9PE': 0,
 'AB15 9PH': 0,
 'AB15 9PQ': 0,
 'AB15 9PT': 0,
 'AB15 9PU': 0,
 'AB15 9QA': 0,
 'AB15 9QB': 0,
 'AB15 9QD': 0,
 'AB15 9QG': 0,
 'AB15 9QH': 0,
 'AB15 9QJ': 0,
 'AB15 9SF': 0,
 'AB15 9SN': 0,
 'AB15 9ST': 0,
 'AB16 5DN': 0,
 'AB16 5GE': 0,
 'AB16 5GJ': 0,
 'AB16 5JP': 0,
 'AB16 5JQ': 0,
 'AB16 5JS': 0,
 'AB16 5NY': 0,
 'AB16 5PU': 0,
 'AB16 5RX': 0,
 'AB16 5UP': 0,
 'AB16 5UQ': 0,
 'AB16 5UW': 0,
 'AB16 5WA': 0,
 'AB16 5WL': 0,
 'AB16 5XP': 0,
 'AB16 5XQ': 0,
 'AB16 5XR': 0,
 'AB16 5XS': 0,
 'AB16 5YA': 0,
 'AB16 5YB': 0,
 'AB16 6DX': 0,
 'AB16 6LA': 0,
 'AB16 6NB': 0,
 'AB16 6QF': 0,
 'AB16 7AF': 0,
 'AB16 7AG': 0,
 'AB16 7AH': 0,
 'AB16 7BE': 0,
 'AB16 7HG': 0,
 'AB16 7PE': 0,
 'AB16 7RF': 0,
 'AB16 7RH': 0,
 'AB16 7RU': 0,
 'AB16 7UE': 0,
 'AB16 9AP': 0,
 'AB16 9BE': 0,
 'AB16 9BT': 0,
 'AB16 9BU': 0,
 'AB16 9BX': 0,
 'AB16 9BY': 0,
 'AB16 9BZ': 0,
 'AB16 9DD': 0,
 'AB16 9DJ': 0,
 'AB16 9DW': 0,
 'AB16 9DX': 0,
 'AB16 9EA': 0,
 'AB16 9SA': 0,
 'AB16 9SB': 0,
 'AB16 9SD': 0,
 'AB16 9SE': 0,
 'AB16 9SF': 0,
 'AB16 9SG': 0,
 'AB16 9SH': 0,
 'AB16 9SJ': 0,
 'AB16 9SL': 0,
 'AB16 9SN': 0,
 'AB16 9SP': 0,
 'AB16 9SQ': 0,
 'AB16 9SR': 0,
 'AB16 9SS': 0,
 'AB16 9ST': 0,
 'AB16 9SU': 0,
 'AB16 9SW': 0,
 'AB16 9SX': 0,
 'AB16 9SY': 0,
 'AB16 9SZ': 0,
 'AB16 9TA': 0,
 'AB16 9TB': 0,
 'AB16 9TD': 0,
 'AB16 9TE': 0,
 'AB16 9TF': 0,
 'AB16 9TG': 0,
 'AB16 9TH': 0,
 'AB16 9TJ': 0,
 'AB16 9TL': 0,
 'AB16 9TN': 0,
 'AB16 9TP': 0,
 'AB16 9TQ': 0,
 'AB16 9TR': 0,
 'AB16 9TS': 0,
 'AB16 9TT': 0,
 'AB16 9TU': 0,
 'AB16 9TW': 0,
 'AB16 9TX': 0,
 'AB16 9TY': 0,
 'AB16 9TZ': 0,
 'AB16 9UA': 0,
 'AB16 9UB': 0,
 'AB16 9UD': 0,
 'AB16 9UE': 0,
 'AB16 9UF': 0,
 'AB16 9UG': 0,
 'AB16 9UH': 0,
 'AB16 9UJ': 0,
 'AB16 9UL': 0,
 'AB16 9UN': 0,
 'AB16 9UP': 0,
 'AB16 9UQ': 0,
 'AB16 9UR': 0,
 'AB16 9US': 0,
 'AB16 9UT': 0,
 'AB16 9UU': 0,
 'AB16 9UW': 0,
 'AB16 9UX': 0,
 'AB16 9UY': 0,
 'AB16 9UZ': 0,
 'AB16 9WA': 0,
 'AB16 9WB': 0,
 'AB16 9WD': 0,
 'AB16 9WE': 0,
 'AB16 9WF': 0,
 'AB16 9WG': 0,
 'AB16 9WH': 0,
 'AB16 9WJ': 0,
 'AB16 9WL': 0,
 'AB16 9WN': 0,
 'AB16 9ZZ': 0,
 'AB21 0BA': 0,
 'AB21 0BL': 0,
 'AB21 0BN': 0,
 'AB21 0BT': 0,
 'AB21 0BU': 0,
 'AB21 0BY': 0,
 'AB21 0BZ': 0,
 'AB21 0DA': 0,
 'AB21 0EQ': 0,
 'AB21 0ET': 0,
 'AB21 0EW': 0,
 'AB21 0EX': 0,
 'AB21 0EY': 0,
 'AB21 0FN': 0,
 'AB21 0GD': 0,
 'AB21 0GZ': 0,
 'AB21 0HA': 0,
 'AB21 0HD': 0,
 'AB21 0HE': 0,
 'AB21 0HH': 0,
 'AB21 0HJ': 0,
 'AB21 0HN': 0,
 'AB21 0HQ': 0,
 'AB21 0HS': 0,
 'AB21 0HT': 0,
 'AB21 0HU': 0,
 'AB21 0HX': 0,
 'AB21 0HY': 0,
 'AB21 0JA': 0,
 'AB21 0JB': 0,
 'AB21 0JD': 0,
 'AB21 0JE': 0,
 'AB21 0JH': 0,
 'AB21 0JJ': 0,
 'AB21 0JL': 0,
 'AB21 0JN': 0,
 'AB21 0JR': 0,
 'AB21 0LL': 0,
 'AB21 0LT': 0,
 'AB21 0LU': 0,
 'AB21 0LW': 0,
 'AB21 0NN': 0,
 'AB21 0NU': 0,
 'AB21 0PB': 0,
 'AB21 0PE': 0,
 'AB21 0PT': 0,
 'AB21 0PX': 0,
 'AB21 0QA': 0,
 'AB21 0QB': 0,
 'AB21 0QE': 0,
 'AB21 0QH': 0,
 'AB21 0QJ': 0,
 'AB21 0QL': 0,
 'AB21 0QN': 0,
 'AB21 0QP': 0,
 'AB21 0QQ': 0,
 'AB21 0QR': 0,
 'AB21 0QS': 0,
 'AB21 0QT': 0,
 'AB21 0QU': 0,
 'AB21 0QW': 0,
 'AB21 0QX': 0,
 'AB21 0QY': 0,
 'AB21 0RB': 0,
 'AB21 0RD': 0,
 'AB21 0RE': 0,
 'AB21 0RH': 0,
 'AB21 0RJ': 0,
 'AB21 0RL': 0,
 'AB21 0RN': 0,
 'AB21 0RP': 0,
 'AB21 0RQ': 0,
 'AB21 0RR': 0,
 'AB21 0RS': 0,
 'AB21 0RT': 0,
 'AB21 0RU': 0,
 'AB21 0RW': 0,
 'AB21 0SA': 0,
 'AB21 0SB': 0,
 'AB21 0SE': 0,
 'AB21 0SP': 0,
 'AB21 0SU': 0,
 'AB21 0SY': 0,
 'AB21 0TA': 0,
 'AB21 0TB': 0,
 'AB21 0TD': 0,
 'AB21 0TE': 0,
 'AB21 0TF': 0,
 'AB21 0TG': 0,
 'AB21 0TH': 0,
 'AB21 0TJ': 0,
 'AB21 0TN': 0,
 'AB21 0TP': 0,
 'AB21 0TQ': 0,
 'AB21 0TR': 0,
 'AB21 0TS': 0,
 'AB21 0TU': 0,
 'AB21 0TY': 0,
 'AB21 0TZ': 0,
 'AB21 0UD': 0,
 'AB21 0UG': 0,
 'AB21 0UL': 0,
 'AB21 0UN': 0,
 'AB21 0UP': 0,
 'AB21 0UQ': 0,
 'AB21 0UR': 0,
 'AB21 0US': 0,
 'AB21 0UX': 0,
 'AB21 0WA': 0,
 'AB21 0WJ': 0,
 'AB21 0WL': 0,
 'AB21 0WP': 0,
 'AB21 0WQ': 0,
 'AB21 0XD': 0,
 'AB21 0XY': 0,
 'AB21 0YA': 0,
 'AB21 0YB': 0,
 'AB21 0YD': 0,
 'AB21 0YE': 0,
 'AB21 0YF': 0,
 'AB21 0YG': 0,
 'AB21 0YL': 0,
 'AB21 0YQ': 0,
 'AB21 0YR': 0,
 'AB21 0YS': 0,
 'AB21 0YT': 0,
 'AB21 0YX': 0,
 'AB21 1AE': 0,
 'AB21 1AN': 0,
 'AB21 1AP': 0,
 'AB21 1AQ': 0,
 'AB21 1AR': 0,
 'AB21 7AH': 0,
 'AB21 7AJ': 0,
 'AB21 7AL': 0,
 'AB21 7AN': 0,
 'AB21 7AP': 0,
 'AB21 7AQ': 0,
 'AB21 7AR': 0,
 'AB21 7AS': 0,
 'AB21 7AT': 0,
 'AB21 7BF': 0,
 'AB21 7BG': 0,
 'AB21 7EU': 0,
 'AB21 7GN': 0,
 'AB21 7GR': 0,
 'AB21 7HF': 0,
 'AB21 7LW': 0,
 'AB21 7NX': 0,
 'AB21 7NY': 0,
 'AB21 7PB': 0,
 'AB21 7PE': 0,
 'AB21 7PH': 0,
 'AB21 7PP': 0,
 'AB21 7PR': 0,
 'AB21 7PS': 0,
 'AB21 7PU': 0,
 'AB21 7PW': 0,
 'AB21 7PY': 0,
 'AB21 7PZ': 0,
 'AB21 7UU': 0,
 'AB21 7XA': 0,
 'AB21 7XB': 0,
 'AB21 7YS': 0,
 'AB21 9AG': 0,
 'AB21 9BG': 0,
 'AB21 9EG': 0,
 'AB21 9FL': 0,
 'AB21 9NS': 0,
 'AB21 9PB': 0,
 'AB21 9PD': 0,
 'AB21 9PE': 0,
 'AB21 9QE': 0,
 'AB21 9SE': 0,
 'AB21 9SN': 0,
 'AB21 9SQ': 0,
 'AB21 9SR': 0,
 'AB21 9SS': 0,
 'AB21 9TD': 0,
 'AB21 9TE': 0,
 'AB21 9TJ': 0,
 'AB21 9TL': 0,
 'AB21 9TX': 0,
 'AB21 9UR': 0,
 'AB21 9WH': 0,
 'AB21 9WJ': 0,
 'AB21 9WL': 0,
 'AB21 9WN': 0,
 'AB21 9WP': 0,
 'AB21 9XU': 0,
 'AB22 8AR': 0,
 'AB22 8AS': 0,
 'AB22 8AW': 0,
 'AB22 8BN': 0,
 'AB22 8ER': 0,
 'AB22 8LS': 0,
 'AB22 8NP': 0,
 'AB22 8NX': 0,
 'AB22 8PJ': 0,
 'AB22 8PT': 0,
 'AB22 8QG': 0,
 'AB22 8WR': 0,
 'AB22 8ZN': 0,
 'AB23 8AD': 0,
 'AB23 8AN': 0,
 'AB23 8AQ': 0,
 'AB23 8AT': 0,
 'AB23 8AX': 0,
 'AB23 8AZ': 0,
 'AB23 8BA': 0,
 'AB23 8BJ': 0,
 'AB23 8BN': 0,
 'AB23 8BR': 0,
 'AB23 8BU': 0,
 'AB23 8DB': 0,
 'AB23 8GH': 0,
 'AB23 8GT': 0,
 'AB23 8HZ': 0,
 'AB23 8NA': 0,
 'AB23 8NN': 0,
 'AB23 8NP': 0,
 'AB23 8NQ': 0,
 'AB23 8NR': 0,
 'AB23 8NS': 0,
 'AB23 8NT': 0,
 'AB23 8PU': 0,
 'AB23 8PZ': 0,
 'AB23 8SD': 0,
 'AB23 8SJ': 0,
 'AB23 8TR': 0,
 'AB23 8UF': 0,
 'AB23 8UL': 0,
 'AB23 8UN': 0,
 'AB23 8UP': 0,
 'AB23 8UQ': 0,
 'AB23 8UR': 0,
 'AB23 8UT': 0,
 'AB23 8UU': 0,
 'AB23 8UX': 0,
 'AB23 8UZ': 0,
 'AB23 8XA': 0,
 'AB23 8XB': 0,
 'AB23 8XE': 0,
 'AB23 8XH': 0,
 'AB23 8XJ': 0,
 'AB23 8XL': 0,
 'AB23 8XN': 0,
 'AB23 8XP': 0,
 'AB23 8XQ': 0,
 'AB23 8XS': 0,
 'AB23 8YA': 0,
 'AB23 8YH': 0,
 'AB23 8YJ': 0,
 'AB23 8YL': 0,
 'AB23 8YN': 0,
 'AB23 8YX': 0,
 'AB23 9AQ': 0,
 'AB23 9AY': 0,
 'AB23 9AZ': 0,
 'AB24 1AW': 0,
 'AB24 1FR': 0,
 'AB24 1GU': 0,
 'AB24 1RF': 0,
 'AB24 1SE': 0,
 'AB24 1SZ': 0,
 'AB24 1TF': 0,
 'AB24 1TG': 0,
 'AB24 1TZ': 0,
 'AB24 1UG': 0,
 'AB24 1WA': 0,
 'AB24 1WB': 0,
 'AB24 1WD': 0,
 'AB24 1WE': 0,
 'AB24 1WF': 0,
 'AB24 1WG': 0,
 'AB24 1WH': 0,
 'AB24 1WJ': 0,
 'AB24 1WL': 0,
 'AB24 1WN': 0,
 'AB24 1WP': 0,
 'AB24 1WQ': 0,
 'AB24 1XF': 0,
 'AB24 1XG': 0,
 'AB24 1XN': 0,
 'AB24 1XT': 0,
 'AB24 1XU': 0,
 'AB24 1ZS': 0,
 'AB24 2BG': 0,
 'AB24 2GE': 0,
 'AB24 2PS': 0,
 'AB24 2TY': 0,
 'AB24 2UL': 0,
 'AB24 2UN': 0,
 'AB24 2UX': 0,
 'AB24 2UY': 0,
 'AB24 2XU': 0,
 'AB24 2XX': 0,
 'AB24 2XY': 0,
 'AB24 2YA': 0,
 'AB24 2YB': 0,
 'AB24 2YD': 0,
 'AB24 2YE': 0,
 'AB24 2YH': 0,
 'AB24 2YJ': 0,
 'AB24 2YX': 0,
 'AB24 3AA': 0,
 'AB24 3AD': 0,
 'AB24 3DF': 0,
 'AB24 3DG': 0,
 'AB24 3EF': 0,
 'AB24 3GZ': 0,
 'AB24 3HQ': 0,
 'AB24 3HW': 0,
 'AB24 3LF': 0,
 'AB24 3LW': 0,
 'AB24 3NA': 0,
 'AB24 3RT': 0,
 'AB24 3SW': 0,
 'AB24 3TS': 0,
 'AB24 3TT': 0,
 'AB24 3UF': 0,
 'AB24 3UG': 0,
 'AB24 3UL': 0,
 'AB24 3UT': 0,
 'AB24 3UW': 0,
 'AB24 3UX': 0,
 'AB24 3WT': 0,
 'AB24 3WU': 0,
 'AB24 3XY': 0,
 'AB24 4AG': 0,
 'AB24 4GB': 0,
 'AB24 4GD': 0,
 'AB24 4LZ': 0,
 'AB24 4SG': 0,
 'AB24 5DY': 0,
 'AB24 5EW': 0,
 'AB24 5HT': 0,
 'AB24 5JU': 0,
 'AB24 5LQ': 0,
 'AB24 5NG': 0,
 'AB24 5NZ': 0,
 'AB24 5PY': 0,
 'AB24 5RG': 0,
 'AB24 5RW': 0,
 'AB24 5SN': 0,
 'AB24 5SW': 0,
 'AB24 5SX': 0,
 'AB24 5TA': 0,
 'AB24 5UA': 0,
 'AB24 5WA': 0,
 'AB24 5WW': 0,
 'AB24 5YF': 0,
 'AB25 1BH': 0,
 'AB25 1BZ': 0,
 'AB25 1DF': 0,
 'AB25 1DG': 0,
 'AB25 1DQ': 0,
 'AB25 1DR': 0,
 'AB25 1DS': 0,
 'AB25 1DU': 0,
 'AB25 1EB': 0,
 'AB25 1EG': 0,
 'AB25 1EW': 0,
 'AB25 1EZ': 0,
 'AB25 1FA': 0,
 'AB25 1FB': 0,
 'AB25 1FD': 0,
 'AB25 1FN': 0,
 'AB25 1GA': 0,
 'AB25 1GR': 0,
 'AB25 1HF': 0,
 'AB25 1HZ': 0,
 'AB25 1JE': 0,
 'AB25 1LD': 0,
 'AB25 1NL': 0,
 'AB25 1NX': 0,
 'AB25 1PH': 0,
 'AB25 1PJ': 0,
 'AB25 1QF': 0,
 'AB25 1RQ': 0,
 'AB25 1TX': 0,
 'AB25 1UP': 0,
 'AB25 1YD': 0,
 'AB25 1YR': 0,
 'AB25 1ZA': 0,
 'AB25 2AY': 0,
 'AB25 2GA': 0,
 'AB25 2UZ': 0,
 'AB25 2XE': 0,
 'AB25 2XF': 0,
 'AB25 2XH': 0,
 'AB25 2YD': 0,
 ...}

In [84]:
dfepc['newgas'] = dfepc.pcode.map(notgas_dict)
dfepc.newgas.fillna(1, inplace=True)
dfepc['mainsgas1'] = np.where(dfepc.mainsgas.isnull(), dfepc.newgas, dfepc.mainsgas)
mains_dict = {'Y': 1, 'N': 0, 1: 1, 0: 0}
dfepc['maingas'] = dfepc.mainsgas1.map(mains_dict)
dfepc.head()

,pcode,bref,curr_enr,curr_encons,prop_type,builtform,la,transact_type,tfa,mainsgas,...,builtmap,exposedsides,type,form,wall_firstword,age,epc_band,newgas,mainsgas1,maingas
0,EC4Y 8DU,3221499468,C,9662,Flat,Detached,City of London,not recorded,48.30,Y,...,0.0,4.0,flat,detached,Wall,1.0,2,1.0,Y,1
1,EC4Y 8DU,2290543668,C,172,Flat,Mid-Terrace,City of London,rental (private),70.85,Y,...,-2.0,2.0,flat,mid-terrace,System,3.0,2,1.0,Y,1
2,EC4Y 8DU,6015699968,C,146,Flat,Mid-Terrace,City of London,marketed sale,66.00,Y,...,-2.0,2.0,flat,mid-terrace,Solid,1.0,2,1.0,Y,1
3,EC4Y 8DU,9939448868,C,139,Flat,Mid-Terrace,City of London,marketed sale,66.00,Y,...,-2.0,2.0,flat,mid-terrace,Solid,1.0,2,1.0,Y,1
4,EC4Y 8DU,1536490868,C,154,Flat,Enclosed Mid-Terrace,City of London,marketed sale,111.00,Y,...,-2.5,1.5,flat,enclosed mid-terrace,Solid,1.0,2,1.0,Y,1

In [85]:
dfepc.maingas.unique()

array([1, 0])

In [91]:
epc_cols = ['bref', 
             'imd', 
             'type', 
             'form', 
             'exposedsides', 
             'tfa', 
             'epc_band', 
             'age', 
             'nroom', 
             'maingas', 
             'gasmid', 
             'elecmid',
             'gasmeters',
             'elecmeters']

temp = dfepc[epc_cols]
temp.head()

rename_cols = ['hid', 
             'imd', 
             'type', 
             'form', 
             'exposedsides', 
             'tfa', 
             'epc', 
             'age', 
             'nroom', 
             'maingas', 
             'gcons', 
             'econs',
             'gmeters',
             'emeters']
temp.columns = rename_cols

In [92]:
temp.nroom.unique()

array([ 1,  3,  4,  2,  5,  6,  8,  7,  9, 10])